#!/bin/sh

export VER='1.1.5'
export MAINVER='1.1.5'
export REV=84
export FEATURES='增加对“地点推荐”模块的屏蔽；增加对“带着微博去旅行”标识的屏蔽；修正无法在用户信息气球中设置屏蔽的问题；修正部分模块无法被屏蔽的问题；修正无法在用户主页打开设置窗口的问题'

while getopts ":nd" optname
do
	case "$optname" in
		"n") COMPRESS=' --nocompress';;
		"d") COMPRESS=' --nocompress'; PARAMS=' --flag=DEBUG';;
		"?") echo "Unknown option -$OPTARG"; exit 1;;
		":") echo "Missing argument value for option -$OPTARG"; exit 1;;
	esac
done

# Greasemonkey
printf 'Building Greasemonkey script...'
export CSS=`./compile.pl $PARAMS --flag=GREASEMONKEY settings.css`
export HTML=`./compile.pl $PARAMS --flag=GREASEMONKEY settings.html`
SCRIPT="release/latest/weiboFilter-v${VER}.user.js"
./compile.pl --nocompress head.js > $SCRIPT
printf '\n' >> $SCRIPT
./compile.pl $COMPRESS $PARAMS --flag=GREASEMONKEY weiboFilter.user.js >> $SCRIPT
unset CSS HTML
echo ' done.'

# Chrome
printf 'Building Chrome extension...'
export CSS=`./compile.pl $PARAMS --flag=CHROME settings.css`
export HTML=`./compile.pl $PARAMS --flag=CHROME settings.html`
rm -f release/latest/chrome/*
cp chrome/* release/latest/chrome/
./compile.pl --nocompress -out="release/latest/chrome/manifest.json" chrome/manifest.json
./compile.pl $COMPRESS $PARAMS --out="release/latest/chrome/main.js" chrome/main.js
./compile.pl $COMPRESS $PARAMS --flag=CHROME --out="release/latest/chrome/weiboFilter.js" weiboFilter.user.js
echo ' done.'

unset VER MAINVER REV